name: Update calendar
description: 'Update calendar content in given file'
inputs:
  calendar_url:
    description: 'Calendar to use - URL to ics file'
    required: true
  file:
    description: 'File to edit'


runs:
  using: composite
  steps:
  - uses: actions/setup-python@v5
    with:
      python-version: '3.13'
      cache: 'pip'
  - run: pip install -U icalendar
    shell: bash
  - run: ${{ github.action_path }}/calendar.py ${{ inputs.file }} > index.html.new
    shell: bash
    env:
      CALENDAR_URL: ${{ inputs.calendar_url }}
  # Only rewrite original file if there's a difference other than blank lines'
  - run: |
      set +e
      diff -B ${{ inputs.file }} index.html.new
      if [[ $? > 0 ]]; then mv index.html.new ${{ inputs.file }}; else rm index.html.new; fi
    shell: bash
