name: Update calendar
description: 'Update calendar content in given file'
inputs:
  calendar_url:
    description: 'Calendar to use - URL to ics file'
    required: true
  file:
    description: 'File to edit'


runs:
  using: composite
  steps:
  - run: pip install -U icalendar
    shell: bash
  - run: ${{ github.action_path }}/calendar.py ${{ inputs.file }} > index.html.tmp
    shell: bash
    env:
      CALENDAR_URL: ${{ inputs.calendar_url }}
  - run: mv index.html.tmp ${{ inputs.file }}
    shell: bash
