name: Update calendar
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:

  deploy:
    name: S3 Sync / CFront cache clear
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
         sparse-checkout: |
           .github

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          unset-current-credentials: true
          aws-region: ${{ vars.AWS_S3_BUCKET_REGION }}
          role-to-assume: ${{ vars.AWS_GH_OIDC_ROLE }}

      - name: Sync index from S3
        run: |
          aws s3 sync s3://${{ vars.AWS_S3_BUCKET }}/www ./ --exclude="*" --include="index.html" --exact-timestamps

      - uses: ./.github/actions/update-calendar 
        with:
          calendar_url: ${{ secrets.CALENDAR_URL }}
          file: index.html

      - name: Sync src to S3
        id: s3_upload
        run: |
          aws s3 sync ./ s3://${{ vars.AWS_S3_BUCKET }}/www --exclude="*" --include="index.html" | tee aws_sync_out.txt
          echo "S3_CHANGED=`grep upload aws_sync_out.txt | wc -l`" >> $GITHUB_OUTPUT
          rm aws_sync_out.txt

      - name: Invalidate CloudFront distribution cache and wait
        if: steps.s3_upload.outputs.S3_CHANGED != '0'
        run: >
          echo ${{ steps.s3_upload.outputs.S3_CHANGED }}
        
          aws cloudfront create-invalidation
          --distribution-id ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          --paths "/*"
          --output json | tee cf_inv.json 

          echo Waiting for Invalidation: $(cat cf_inv.json | jq -r .Invalidation.Id)
    
          aws cloudfront wait invalidation-completed
          --distribution-id ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          --id $(cat cf_inv.json | jq -r .Invalidation.Id)
